CREATE TABLE `games` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `JamID` int(11) NOT NULL,
  `UserID` int(11) NOT NULL,
  `Name` text NOT NULL,
  `Description` text NOT NULL,
  `Partner` text NOT NULL,
  `SourceLink` text NOT NULL,
  `ProjectLink` text NOT NULL,
  `LogoLink` text NOT NULL,
  `Screen1` text NOT NULL,
  `Screen2` text NOT NULL,
  `Screen3` text NOT NULL,
  `WindowsLink` text NOT NULL,
  `LinuxLink` text NOT NULL,
  `OSXLink` text NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `GMFKJamID_idx` (`JamID`),
  KEY `GMFKUserID_idx` (`UserID`),
  CONSTRAINT `GMFKJamID` FOREIGN KEY (`JamID`) REFERENCES `jams` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `GMFKUserID` FOREIGN KEY (`UserID`) REFERENCES `users` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)