CREATE TABLE `votes` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `JamID` int(11) NOT NULL,
  `ThemeID` int(11) NOT NULL,
  `UserID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `VTFKJamID_idx` (`JamID`),
  KEY `VTFKThemeID_idx` (`ThemeID`),
  KEY `VTFKUserID_idx` (`UserID`),
  CONSTRAINT `VTFKJamID` FOREIGN KEY (`JamID`) REFERENCES `jams` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `VTFKThemeID` FOREIGN KEY (`ThemeID`) REFERENCES `themes` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `VTFKUserID` FOREIGN KEY (`UserID`) REFERENCES `users` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)